### PR TITLE
Adding a store listing feature

### PR DESCRIPTION
**Pull request by samuelwang48**
Usage Example:
$ got-weed stores [en|fr]

### CODE REVIEW

**Comment by millette** [comment]
Thanks @samuelwang48 for the contrib. I'll be merging this soon and update the cli arguments to use flags.

**Comment by samuelwang48** [comment]
@millette Bienvenue! Glad to hear that!

**Comment by millette** [comment]
Seems there is no difference between languages for the stores. I'll handle that next.

And unit tests, while I'm at it :-)

Bonne soirée!

**Comment by samuelwang48** [comment]
Let me know if you have any new ideas by creating new issues here so I can share some of the workload :)

**Comment by millette** [comment]
https://github.com/millette/got-weed/releases/tag/v0.0.3 :-)

**Comment by millette** [comment]
There, we got [a few issues](https://github.com/millette/got-weed/issues) to get us started.

**Pull request merged**
